# กำหนด network
networks:
  spring_staging_network:
    name: spring_staging_network
    driver: bridge

# กำหนด service
services:
  stagingdb:
    image: postgres:15.2
    container_name: bookdb-${ENV}
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: bookdb
    volumes:
      - ./pgstagingdb:/var/lib/postgresql/data
    ports:
      - "8432:5432"
    networks:
      - spring_staging_network
  stagingapi:
    image: bookapi-api-${ENV}"
    build:
      context: .
      dockerfile: Dockerfile-${ENV}
    ports:
      - "9090:9090"
    container_name: bookapi-${ENV}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stagingdb:5432/bookdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    depends_on:
      - stagingdb
    restart: always
    networks:
      - spring_staging_network

# กำหนด volume
volumes:
  pgstagingdb:
    driver: local