# กำหนด network
networks:
  spring_production_network:
    name: spring_production_network
    driver: bridge

# กำหนด service
services:
  proddb:
    image: postgres:15.2
    container_name: bookdb-${ENV}
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: bookdb
    volumes:
      - ./pgproddb:/var/lib/postgresql/data
    ports:
      - "9432:5432"
    networks:
      - spring_production_network
  prodapi:
    image: bookapi-api-${ENV}"
    build:
      context: .
      dockerfile: Dockerfile-${ENV}
    ports:
      - "9191:9191"
    container_name: bookapi-${ENV}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://proddb:5432/bookdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    depends_on:
      - proddb
    restart: always
    networks:
      - spring_production_network

# กำหนด volume
volumes:
  pgproddb:
    driver: local